### ISSUE TITLE
While clicking a post/group to submit, I receive a 500 error

### ISSUE THREAD

**Issue by urcades** [sdockray/sma#1]
Here's a pic of what I get —

![screen shot 2015-05-13 at 11 56 25 am](https://cloud.githubusercontent.com/assets/1195363/7616042/3b879dbc-f967-11e4-8045-135012f35d3c.png)

And the text is pasted here:

```
Traceback (most recent call last):
  File "/srv/http/sma/venv2/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/srv/http/sma/venv2/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/srv/http/sma/venv2/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/srv/http/sma/sma/server.py", line 168, in fb
    fb.archive_post(value)
  File "/srv/http/sma/sma/archiver.py", line 442, in archive_post
    a = PostArchive(self.g, id)
  File "/srv/http/sma/sma/archiver.py", line 214, in __init__
    self.file_load(filename)
  File "/srv/http/sma/sma/archiver.py", line 230, in file_load
    if 'obj' in d:
TypeError: argument of type 'NoneType' is not iterable
```

Thanks!

**Comment by urcades** [comment]
Forgot to mention, Chrome/OS version information —

```

Google Chrome   44.0.2391.0 (Official Build) dev (64-bit)
Revision    f452b25283d9e3669a63b40b12d41457d5798d46-refs/heads/master@{#328082}
OS  Mac OS X 
Blink   537.36 (@194849)
JavaScript  V8 4.4.48.1
Flash   17.0.0.188
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2391.0 Safari/537.36
Command Line    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_45067 --restore-last-session --enable-avfoundation --flag-switches-begin --flag-switches-end
Executable Path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path    /Users/edouardurcadez/Library/Application Support/Google/Chrome/Profile 1
Variations  47f591a-817b2a89
22fd1d6c-7461cf66
6345b824-3f4a17df
e950616e-65b8dcc0
e9f4800b-39c30599
8afebf76-41e080dc
19f73432-ca7d8d80
76b48ab8-a2567007
c70841c8-4866ef6e
8472fcfc-ca7d8d80
29f8fea-dffbf7ac
195ce1b5-d93a0620
9d315c2-ca7d8d80
a3e00cc3-3d47f4f4
b2638b4d-3f4a17df
1d3ad72e-3f4a17df
9e5c75f1-7ad3e432
f79cb77b-3d47f4f4
89ddaf11-6fd07e77
3100b8ed-3f4a17df
ca65a9fe-91ac3782
4ea303a6-45fa0b
fa99bb73-3f4a17df
61544484-ca7d8d80
9736de91-3f4a17df
b2612322-f8cf70e2
c99b9cf4-3f4a17df
be53c1f1-27454201
244ca1ac-4ad60575
3ac60855-486e2a9c
f296190c-f911fcfa
4442aae2-7158671e
ed1d377-e1cc0f14
75f0f0a0-4ad60575
e2b18481-7158671e
e7e71889-e1cc0f14
b39ea213-3d47f4f4
58a405fc-669a04e0
19f5afcc-4ad60575
8361e34b-f23d1dea
cbf0c14e-bf3e6cfd
63dfca2a-f23d1dea
2cdf235f-f23d1dea
9d45295a-ca7d8d80
```

![selfie-0](http://i.imgur.com/sPHohHZ.png)

**Comment by sdockray** [comment]
thanks edouerd - i'm hoping that https://github.com/sdockray/sma/commit/2a262dbde12e00ddfa1d0a7be271d4fef963dd7b will have fixed the issue -s
